language: php

sudo: true
dist: trusty

php:
    - 7.1
    - 7.0
    - 5.6
    - 5.5
    - 5.4
    - 5.3

install:
    - sudo apt-get -qq update
    - sudo apt-get install -y asciidoc libarchive-dev curl libgpgme11-dev
    - curl -O https://sources.archlinux.org/other/pacman/pacman-5.0.1.tar.gz
    - tar -xzvf pacman-5.0.1.tar.gz
    - cd pacman-5.0.1 && ./configure --prefix=/usr && make && sudo make install
    - cd ..

script:
    - export TEST_PHP_EXECUTABLE=`which php`
    - phpize
    - ./configure --with-alpm && make
    - php run-tests.php -d extension=alpm.so -d extension_dir=modules -n ./tests/*.phpt
    - for i in `ls tests/*.out 2> /dev/null`; do echo "-- START ${i}"; cat $i; echo "-- END"; done
