language: php

sudo: true
dist: bionic

php:
    - 7.3
    - 7.2
    - 7.1

env:
    - PACMAN_VERSION=git
    - PACMAN_VERSION=5.0.2
    - PACMAN_VERSION=5.1.2

before_script:
    - bash install_pacman.sh "${PACMAN_VERSION}"

script:
    - export TEST_PHP_EXECUTABLE=`which php`
    - phpize
    - ./configure --with-alpm && make
    - php run-tests.php -d extension=alpm.so -d extension_dir=modules -n ./tests/*.phpt
    - for i in `ls tests/*.out 2> /dev/null`; do echo "-- START ${i}"; cat $i; echo "-- END"; done

matrix:
  allow_failures:
    - env: PACMAN_VERSION=git
